apiVersion: jaegertracing.io/v1
kind: "Jaeger"
metadata:
  name: all-in-one
  namespace: tracing
spec:
  allInOne:
    options:
      query:
        base-path: /jaeger
  ingress:
    enabled: true
    paths:
      - /jaeger
  storage:
    options:
      memory:
        max-traces: 100000
