prometheusOperator:
  createCustomResource: false
  admissionWebhooks:
    enabled: false
  tlsProxy:
    enabled: false

defaultRules:
  rules:
    etcd: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

prometheus:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    paths:
    - /prometheus(/|$)(.*)
  prometheusSpec:
    externalUrl: http://localhost/prometheus
    image:
      tag: v2.20.1
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    paths:
    - /alertmanager(/|$)(.*)
  alertmanagerSpec:
    externalUrl: http://localhost/alertmanager

  config:
    global:
      slack_api_url: https://hooks.slack.com/services/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

    route:
      receiver: 'slack'
      routes: []

    receivers:
    - name: 'slack'
      slack_configs:
      - channel: '#alerts'
        send_resolved: true

grafana:
  image:
    tag: 7.1.4
  ingress:
    enabled: true
    path: /grafana

  sidecar:
    dashboards:
      searchNamespace: ALL

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Jaeger
          type: jaeger
          uid: jaeger
          url: http://all-in-one-query.tracing:16686/jaeger
          access: proxy
          isDefault: false
        - name: Loki
          type: loki
          url: http://loki.logging:3100
          access: proxy
          isDefault: false
          jsonData:
            maxLines: 1000
            derivedFields:
              - name: "TraceID"
                matcherRegex: "traceID=(\\w+)"
                url: "$${__value.raw}"
                datasourceUid: jaeger

  grafana.ini:
    server:
      domain: localhost
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  admin:
    existingSecret: grafana-admin
